# Generated by Django 4.0.1 on 2022-02-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_redditpost_job_id_twitterpost_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='twitterpost',
            name='job_id',
        ),
    ]
