# Generated by Django 4.0.1 on 2022-02-25 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_id', models.BigIntegerField()),
                ('twitter_name', models.CharField(max_length=255)),
                ('twitter_screen_name', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=555)),
                ('access_secret', models.CharField(max_length=555)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('pause', models.BooleanField(default=False)),
                ('twitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_message', to='social.twitter')),
            ],
        ),
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reddit_name', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=555)),
                ('message', models.TextField(blank=True, null=True)),
                ('pause', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reddit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('twitter_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to='social.twittermessage')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instagram', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
