# Generated by Django 4.0.1 on 2022-02-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_sender_id_messagesender_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterMessageSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('twitter_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='social.twittermessage')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageSender',
        ),
    ]
