# Generated by Django 4.0.1 on 2022-02-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_twittermessagesender_delete_messagesender'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('pause', models.BooleanField(default=False)),
                ('reddit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_message', to='social.reddit')),
            ],
        ),
        migrations.CreateModel(
            name='RedditMessageSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('reddit_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='social.redditmessage')),
            ],
        ),
    ]
